[build]
  command = "npm run build"
  publish = ".next"

# Serverless functions config
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Lock Node for both build and functions
[build.environment]
  NODE_VERSION = "18"

# Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# ---------------- Redirects ----------------

# Pretty URL for the static page at public/ar/pin.html
[[redirects]]
  from = "/ar/pin"
  to = "/ar/pin.html"
  status = 200
  force = true

[[redirects]]
  from = "/ar/pin/"
  to = "/ar/pin.html"
  status = 200
  force = true

# Legacy paths -> new page
[[redirects]]
  from = "/ar/drop-pin"
  to = "/ar/pin.html"
  status = 301
  force = true

[[redirects]]
  from = "/ar/drop-pin/"
  to = "/ar/pin.html"
  status = 301
  force = true
